foreground              #efe0d5
background              #19120c
selection_foreground    #4a2800
selection_background    #fdb975

cursor                  #fdb975
cursor_text_color       #4a2800
url_color               #fdb975

active_border_color     #fdb975
inactive_border_color   #51453a
bell_border_color       #ffb4ab

active_tab_foreground   #4a2800
active_tab_background   #fdb975
inactive_tab_foreground #d5c3b5
inactive_tab_background #51453a
tab_bar_background      #19120c

color0                #19120c
color1                #ffb4ab
color2                #c0cc9a
color3                #e1c1a4
color4                #fdb975
color5                #c0cc9a
color6                #e1c1a4
color7                #efe0d5

color8                #51453a
color9                #93000a
color10               #414b24
color11               #59422d
color12               #6a3c01
color13               #59422d
color14               #414b24
color15               #d5c3b5