foreground              #e2e2e2
background              #131313
selection_foreground    #1b1b1b
selection_background    #ffffff

cursor                  #ffffff
cursor_text_color       #1b1b1b
url_color               #ffffff

active_border_color     #ffffff
inactive_border_color   #474747
bell_border_color       #ffb4ab

active_tab_foreground   #1b1b1b
active_tab_background   #ffffff
inactive_tab_foreground #c6c6c6
inactive_tab_background #474747
tab_bar_background      #131313

color0                #131313
color1                #ffb4ab
color2                #e2e2e2
color3                #c6c6c6
color4                #ffffff
color5                #474747
color6                #ababab
color7                #e2e2e2

color8                #474747
color9                #93000a
color10               #919191
color11               #474747
color12               #d4d4d4
color13               #3b3b3b
color14               #e2e2e2
color15               #c6c6c6