window_padding_width 25
hide_window_decorations yes
confirm_os_window_close 0

font_size 9.0
font_family JetBrainsMono NF
bold_font auto
italic_font auto
bold_italic_font auto

cursor_shape block
cursor_blink_interval 0

map ctrl+c copy_or_to_clipboard
map ctrl+v paste_from_clipboard

remember_window_size no
initial_window_width 800
initial_window_height 500

include colors.conf
