[config]
reload_apps = false

[templates.rofi]
input_path  = '~/.config/matugen/templates/colors.rasi'
output_path = '~/.config/rofi/colors.rasi'

[templates.dunst]
input_path  = '~/.config/matugen/templates/dunstrc'
output_path = '~/.config/dunst/dunstrc'
post_hook   = 'dunstctl reload'

[templates.kitty]
input_path  = '~/.config/matugen/templates/colors.conf'
output_path = '~/.config/kitty/colors.conf'
post_hook   = 'kill -SIGUSR1 $(pgrep kitty)'

[templates.waybar]
input_path  = '~/.config/matugen/templates/colors.css'
output_path = '~/.config/waybar/colors.css'
post_hook   = 'pkill -SIGUSR2 waybar'

[templates.hyprlock]
input_path  = '~/.config/matugen/templates/lockscreen.conf'
output_path = '~/.config/hypr/other/lockscreen.conf'

[templates.gtk4]
input_path  = '~/.config/matugen/templates/gtkcolors.css'
output_path = '~/.config/gtk-4.0/colors.css'

[templates.papirus-folders]
input_path = '~/.config/matugen/templates/papirus'
compare_to = '{{colors.primary.default.hex}}'
post_hook = 'papirus-folders -C {{closest_color}} -o && nautilus -q'

colors_to_compare = [
  { name = "black", color = "#4f4f4f" }
]