input {
    kb_layout = us,ru
    kb_options = grp:alt_shift_toggle
}

monitor = HDMI-A-1, 1920x1080@120, 0x0, 1

exec-once = awww-daemon 
exec-once = hypridle
exec-once = waybar
exec-once = dunst

general {
    border_size = 0
}

decoration {
    rounding = 9
}

animations {
    enabled = yes
    bezier = myBezier, 0.05, 0.9, 0.1, 1.05
    animation = windows,     1, 4, myBezier
    animation = windowsOut,  1, 4, default, popin 80%
    animation = border,      1, 7, default
    animation = borderangle, 1, 5, default
    animation = fade,        1, 4, default
    animation = workspaces,  1, 3, default
}

# >> if you need this - uncomment this
# bind  = SUPER, P, togglefloating
# bindm = SUPER, mouse:272, movewindow
# bindm = SUPER, mouse:273, resizewindow

bind = SUPER, W, exec, flatpak run com.google.Chrome
bind = SUPER, E, exec, nautilus
bind = SUPER, R, exec, rofi -show drun
bind = SUPER, T, exec, kitty
bind = SUPER, Q, killactive
bind = SUPER, S, exec, grim -g "$(slurp)" - | wl-copy
bind = SUPER, L, exec, hyprlock

bind = SUPER, 1, workspace, 1
bind = SUPER, 2, workspace, 2
bind = SUPER, 3, workspace, 3
bind = SUPER, 4, workspace, 4
bind = SUPER, 5, workspace, 5

# if your keyboard have volume wheel - uncomment this (tested on ajazz ak820)
# bindel = , XF86AudioRaiseVolume, exec, wpctl set-volume -l 1 @DEFAULT_AUDIO_SINK@ 5%+
# bindel = , XF86AudioLowerVolume, exec, wpctl set-volume @DEFAULT_AUDIO_SINK@ 5%-
