$primary       = rgba(fdb975ff)
$on_primary    = rgba(4a2800ff)
$secondary     = rgba(e1c1a4ff)
$surface       = rgba(19120cff)
$on_surface    = rgba(efe0d5ff)
$surface_dim   = rgba(19120cff)
$outline       = rgba(9e8e81ff)
$error         = rgba(ffb4abff)
