$background = rgb({{colors.background.default.rgb}})
$foreground = rgb({{colors.on_background.default.rgb}})
$accent = rgb({{colors.primary.default.rgb}})
$muted = rgb({{colors.on_surface_variant.default.rgb}})
$borders = rgb({{colors.outline.default.rgb}})
